version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: maven
    directory: "/transaction-analyzer/java"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "hantsy"
    assignees:
      - "hantsy"
    labels:
      - "dependencies"
      - "maven"
      
  - package-ecosystem: "maven"
    directory: "/transaction-analyzer/java-fn"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "maven"
    directory: "/transaction-analyzer/java-ddd"
    schedule:
      interval: "weekly"    
      
  - package-ecosystem: "maven"
    directory: "/transaction-analyzer/kotlin"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "composer"
    directory: "/transaction-analyzer/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/transaction-analyzer/node-typescript"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/transaction-analyzer/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/transaction-analyzer/csharp"
    schedule:
      interval: "weekly"
