name: Scala CI

on:
  push:
    paths:
      - "transaction-analyzer/scala/**"
    branches: [ master ]
  pull_request:
    paths:
      - "transaction-analyzer/scala/**"
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#     - name: Set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'

    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v14
      with:
        java-version: "adopt@1.16.0-1"

    - name: Cache sbt
      uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - name: Run tests
      run: |
        cd transaction-analyzer/scala
        sbt test
