name: Go

on:
  push:
    paths:
      - "transaction-analyzer/go/**"
    branches: [ master ]
  pull_request:
    paths:
      - "transaction-analyzer/go/**"
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.16

    - name: Build
      run: |
        cd transaction-analyzer/go
        go build -v ./...

    - name: Test
      run: |
        cd transaction-analyzer/go
        go test -v ./...
