name: .NET

on:
  push:
    paths:
      - "transaction-analyzer/csharp/**"
    branches: [ master ]
  pull_request:
    paths:
      - "transaction-analyzer/csharp/**"
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd transaction-analyzer/csharp
        dotnet restore
    - name: Build
      run: |
        cd transaction-analyzer/csharp
        dotnet build --no-restore
    - name: Test
      run: |
        cd transaction-analyzer/csharp
        dotnet test --no-build --verbosity normal
