# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: kotlin

on:
  push:
    paths:
      - "transaction-analyzer/kotlin/**"
    branches: [ master ]
  pull_request:
    paths:
      - "transaction-analyzer/kotlin/**"
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd transaction-analyzer/kotlin
        mvn -B package --file pom.xml
